# Generated by Django 5.1.5 on 2025-02-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_sos_count"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BotUsers",
            new_name="BotUser",
        ),
        migrations.AlterModelTable(
            name="botuser",
            table="bot_user",
        ),
    ]
