# Generated by Django 5.1.5 on 2025-02-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_botusers_botuser_alter_botuser_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bot_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="users.botuser",
                verbose_name="Bot foydalanuvchisi",
            ),
        ),
    ]
