# Generated by Django 5.1.5 on 2025-02-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_bot_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vip",
            field=models.BooleanField(default=False, verbose_name="VIP"),
        ),
    ]
