# Generated by Django 5.1.5 on 2025-02-18 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(db_index=True, verbose_name="Longitude"),
                ),
                ("latitude", models.FloatField(db_index=True, verbose_name="Latitude")),
                (
                    "address",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "paper_count",
                    models.BigIntegerField(db_index=True, verbose_name="Paper Count"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
                "db_table": "station",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Name"
                    ),
                ),
                ("video", models.FileField(upload_to="videos/", verbose_name="Video")),
                (
                    "duration",
                    models.BigIntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Duration"
                    ),
                ),
                (
                    "hls",
                    models.FileField(
                        blank=True, null=True, upload_to="hls/", verbose_name="HLS"
                    ),
                ),
                (
                    "views",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Views"
                    ),
                ),
                (
                    "position",
                    models.BigIntegerField(
                        db_index=True, default=0, verbose_name="Position"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "stations",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="advertisements",
                        to="backend.station",
                        verbose_name="Stations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
                "db_table": "advertisement",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="StationCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("auth_uri", models.CharField(max_length=255, verbose_name="Auth URI")),
                (
                    "client_id",
                    models.CharField(max_length=255, verbose_name="Client ID"),
                ),
                ("secret", models.CharField(max_length=255, verbose_name="Secret")),
                ("device", models.CharField(max_length=255, verbose_name="Device")),
                ("host", models.CharField(max_length=255, verbose_name="Host")),
                ("password", models.CharField(max_length=255, verbose_name="Password")),
                (
                    "station",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_credentials",
                        to="backend.station",
                        verbose_name="Station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station Credential",
                "verbose_name_plural": "Station Credentials",
                "db_table": "station_credential",
                "ordering": ["-created_at"],
            },
        ),
    ]
