# Generated by Django 5.1.5 on 2025-02-18 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="video",
            field=models.FileField(
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "mkv", "mov"])
                ],
                verbose_name="Video",
            ),
        ),
    ]
